/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Classes.Livro;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Brenda
 */
public class JFListaLivros extends javax.swing.JFrame {

    /**
     * Creates new form JFListaLivros
     */
    public JFListaLivros(JDesktopPane jdp) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jBConsultaLivro = new javax.swing.JButton();
        jBExibeLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextLista = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta e Lista");
        setBackground(new java.awt.Color(189, 222, 240));

        jPanel1.setBackground(new java.awt.Color(189, 222, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta e Lista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome");

        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });

        jBConsultaLivro.setBackground(new java.awt.Color(0, 204, 204));
        jBConsultaLivro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBConsultaLivro.setText("Consultar Livro");
        jBConsultaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultaLivroActionPerformed(evt);
            }
        });

        jBExibeLista.setBackground(new java.awt.Color(0, 204, 204));
        jBExibeLista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBExibeLista.setText("Exibir  todos  os livros");
        jBExibeLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExibeListaActionPerformed(evt);
            }
        });

        TextLista.setColumns(20);
        TextLista.setRows(5);
        TextLista.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextListaComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextListaComponentRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(TextLista);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBExibeLista)
                        .addGap(384, 384, 384))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBConsultaLivro)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 53, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jBConsultaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExibeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextListaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextListaComponentAdded

    }//GEN-LAST:event_TextListaComponentAdded

    private void TextListaComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextListaComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextListaComponentRemoved

    private void jBExibeListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExibeListaActionPerformed

        Livro livro = new Livro();
        try {
            TextLista.setText((livro.listaLivro().toString()));
        } catch (IOException ex) {
            Logger.getLogger(JFListaLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBExibeListaActionPerformed

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jBConsultaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultaLivroActionPerformed

        try {

            String nome = jTxtNome.getText();
            Livro livro = new Livro();

            TextLista.setText((livro.consultaLivro(nome,livro.criaArrayLivro()).toString()));

        } catch (IOException E) {
            JOptionPane.showMessageDialog(rootPane, E.getMessage(), "ERRO!", 2);
        }

    }//GEN-LAST:event_jBConsultaLivroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea TextLista;
    private javax.swing.JButton jBConsultaLivro;
    private javax.swing.JButton jBExibeLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables

}
