/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author yuri-
 */
public class JFrameMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenu
     */
    public JFrameMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        autores = new javax.swing.JButton();
        livros = new javax.swing.JButton();
        locadores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema Bibliotecário ");

        autores.setText("Autores");
        autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoresActionPerformed(evt);
            }
        });

        livros.setText("Livros");
        livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosActionPerformed(evt);
            }
        });

        locadores.setText("Locadores");
        locadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(livros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(autores)
                .addGap(41, 41, 41)
                .addComponent(locadores)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autores)
                    .addComponent(livros)
                    .addComponent(locadores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosActionPerformed
        this.setVisible(false);
        JFrameLivro menuLivro = new JFrameLivro();
        menuLivro.setLocationRelativeTo(null);
        menuLivro.setVisible(true);
    }//GEN-LAST:event_livrosActionPerformed

    private void autoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoresActionPerformed
        this.setVisible(false);
        JFrameAutor menuAutor = new JFrameAutor();
        menuAutor.setLocationRelativeTo(null);
        menuAutor.setVisible(true);
    }//GEN-LAST:event_autoresActionPerformed

    private void locadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locadoresActionPerformed
        this.setVisible(false);
        JFrameLocador menuLocador = new JFrameLocador();
        menuLocador.setLocationRelativeTo(null);
        menuLocador.setVisible(true);
    }//GEN-LAST:event_locadoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton livros;
    private javax.swing.JButton locadores;
    // End of variables declaration//GEN-END:variables
}
